version: '2'

services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    environment:
        - SQLITE_DATABASE=db
        - NEXTCLOUD_ADMIN_USER=admin
        - NEXTCLOUD_ADMIN_PASSWORD=whatever
    ports:
        - 8080:80
    volumes:
        - ./src/:/var/www/html/custom_apps

